In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/11.medgemma-1_5-4b-it /combined_exam_dataset_medgemma-1.5-4b-it.pickle')
df

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025,Varón de 65 años con antecedente de hipertensi...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025,Mujer de 32 años asintomática que acude por ch...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025,¿Cuál es el sitio más frecuente de implantació...,<unused94>thought\n1. **Identify the core que...,medgemma-1.5-4b-it
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 43 años, llevado a urgencias porque s...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 27 años, acude a consulta por visión ...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8375,Gestante de 20 años con 10 semanas de embarazo...,Epigastralgia,Meteorismo,Pérdida de peso menor al 5%,Presencia de aliento fétido,E,Alteraciones hidroelectrolíticas,Ginecología y Obstetricia,Year2020,2020,Gestante de 20 años con 10 semanas de embarazo...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
8376,"Mujer de 40 años ha tenido 4 partos eutócicos,...",Mola hidatidiforme,Hematometra,Tumor anexial,Miomatosis uterina,A,Embarazo gemelar,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años ha tenido 4 partos eutócicos,...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
8377,"Mujer de 40 años, refiere menstruaciones regul...",Biopsia en sacabocado y curetaje cervical,Histerectomía inmediata y extirpación de,Repetir el frotis de Papanicolaou y control a los,Colposcopía con biopsia,D,Dilatación y legrado fraccionado,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años, refiere menstruaciones regul...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
8378,"De los siguientes exámenes o procedimientos, ¿...",Eco transvaginal,Eco doppler transvaginal,Cultivo de secreción vaginal,Histeroscopía,E,Laparoscopia,Ginecología y Obstetricia,Year2020,2020,"De los siguientes exámenes o procedimientos, ¿...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it
8379,Si usted fuera el encargado de determinar que ...,Bloqueo tubárico,DIU,Preservativo,Diafragma,E,Vasectomía,Ginecología y Obstetricia,Year2020,2020,Si usted fuera el encargado de determinar que ...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it

In [3]:
# df['letra_respuesta'] = df['answer_llm'].str.extract(r'Respuesta final: ([ABCDE])')
# df['letra_respuesta'] = df['answer_llm'].str.extract(r'Respuesta final:\(?([ABCDE])\)?')
df['letra_respuesta'] = df['answer_llm'].str.extract(r'Respuesta final:\s?\(?([ABCDE])\)?')
df

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename,letra_respuesta
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025,Varón de 65 años con antecedente de hipertensi...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,A
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025,Mujer de 32 años asintomática que acude por ch...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,C
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025,¿Cuál es el sitio más frecuente de implantació...,<unused94>thought\n1. **Identify the core que...,medgemma-1.5-4b-it,B
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 43 años, llevado a urgencias porque s...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,C
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 27 años, acude a consulta por visión ...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8375,Gestante de 20 años con 10 semanas de embarazo...,Epigastralgia,Meteorismo,Pérdida de peso menor al 5%,Presencia de aliento fétido,E,Alteraciones hidroelectrolíticas,Ginecología y Obstetricia,Year2020,2020,Gestante de 20 años con 10 semanas de embarazo...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,D
8376,"Mujer de 40 años ha tenido 4 partos eutócicos,...",Mola hidatidiforme,Hematometra,Tumor anexial,Miomatosis uterina,A,Embarazo gemelar,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años ha tenido 4 partos eutócicos,...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,A
8377,"Mujer de 40 años, refiere menstruaciones regul...",Biopsia en sacabocado y curetaje cervical,Histerectomía inmediata y extirpación de,Repetir el frotis de Papanicolaou y control a los,Colposcopía con biopsia,D,Dilatación y legrado fraccionado,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años, refiere menstruaciones regul...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,C
8378,"De los siguientes exámenes o procedimientos, ¿...",Eco transvaginal,Eco doppler transvaginal,Cultivo de secreción vaginal,Histeroscopía,E,Laparoscopia,Ginecología y Obstetricia,Year2020,2020,"De los siguientes exámenes o procedimientos, ¿...",<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,A
8379,Si usted fuera el encargado de determinar que ...,Bloqueo tubárico,DIU,Preservativo,Diafragma,E,Vasectomía,Ginecología y Obstetricia,Year2020,2020,Si usted fuera el encargado de determinar que ...,<unused94>thought\n1. **Analyze the Request:*...,medgemma-1.5-4b-it,B

In [4]:
df['letra_respuesta'].value_counts(dropna = False)

letra_respuesta
C      2564
A      1822
B      1701
D      1241
E       821
NaN     231
Name: count, dtype: int64

In [5]:
df[df['letra_respuesta'].isna()][['question', 'answer_llm', 'letra_respuesta']]   # Manually verified that these 09 cases do not contain a valid answer.

,question,answer_llm,letra_respuesta
64,Mujer de 23 años es llevada a consulta por pre...,<unused94>thought\n1. **Analyze the Request:*...,NaN
69,"Escolar de 8 años, presenta desde hace cinco d...",<unused94>thought\n1. **Analyze the Request:*...,NaN
116,"Varón de 45 años, hace 3 meses presenta fatiga...",<unused94>thought\n1. **Analyze the Request:*...,NaN
131,Primigesta de 8 semanas de gestación acude a s...,<unused94>thought\n1. **Analyze the Request:*...,NaN
221,"Varón de 62 años, postoperado de laparotomía e...",<unused94>thought\n1. **Analyze the Request:*...,NaN
...,...,...,...
8234,Un niño de 15 días de nacido es llevado Emerge...,<unused94>thought\n1. **Analyze the Request:*...,NaN
8326,Multigesta de 36 semanas acude a emergencia pa...,<unused94>thought\n1. **Analyze the Request:*...,NaN
8334,El partograma de la OMS trae impreso la línea ...,<unused94>thought\n1. **Analyze the Request:*...,NaN
8358,Mujer de 21 años puérpera de 24 horas de su pr...,<unused94>thought\n1. **Identify the core que...,NaN
8374,Mujer de 24 años se retiró DIU por dolor pélvi...,<unused94>thought\n1. **Analyze the Request:*...,NaN

In [6]:
df = df.dropna(subset='letra_respuesta')
df = df.reset_index(drop=True)
df.shape

(8149, 14)

########################################################################################################################################################################################################

In [7]:
pd.crosstab(df['correct_answer'], df['letra_respuesta'], normalize='columns')

letra_respuesta         A         B         C         D         E
correct_answer
A                0.577936  0.113463  0.117005  0.081386  0.119367
B                0.122942  0.593180  0.147426  0.082998  0.120585
C                0.119100  0.119342  0.479719  0.094279  0.107186
D                0.127333  0.125220  0.181357  0.694601  0.098660
E                0.052689  0.048795  0.074493  0.046737  0.554202

In [8]:
df['is_correct'] = df['correct_answer'] == df['letra_respuesta']

results = df.groupby(['source_file', 'year']).agg(
    count_of_matches=('is_correct', 'sum'),
    total_rows=('is_correct', 'size')
).reset_index()
results['percent_correct'] = (results['count_of_matches'] / results['total_rows']) * 100
results['percent_correct'] = results['percent_correct'].round(2)
# results['performance'] = (results['percent_correct'] >= 52).astype(int)
# results[results['performance'] == 1]
results

,source_file,year,count_of_matches,total_rows,percent_correct
0,Anatomía Patológica & Patología,2018,63,96,65.62
1,Anatomía Patológica & Patología,2019,51,96,53.12
2,Anatomía Patológica & Patología,2020,54,99,54.55
3,Anatomía Patológica & Patología,2023,64,99,64.65
4,Anatomía Patológica & Patología,2024,61,99,61.62
...,...,...,...,...,...
78,Urología,2020,57,100,57.00
79,Urología,2022,53,100,53.00
80,Urología,2023,59,98,60.20
81,Urología,2024,52,99,52.53
82,Urología,2025,55,98,56.12

In [9]:
results['model_name'] = 'medgemma-1.5-4b-it'
results.to_pickle('/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/11.medgemma-1_5-4b-it /_Results.pickle')