In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/10.OctoMed-7B/Chunk_1/combined_exam_dataset_OctoMed-7B_chunk1.pickle')
df

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025,Varón de 65 años con antecedente de hipertensi...,"<think>Okay, let's tackle this medical questio...",OctoMed-7B
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025,Mujer de 32 años asintomática que acude por ch...,"<think>Okay, let's tackle this medical questio...",OctoMed-7B
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025,¿Cuál es el sitio más frecuente de implantació...,"<think>Okay, the question is asking about the ...",OctoMed-7B
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 43 años, llevado a urgencias porque s...","<think>Okay, let's tackle this medical questio...",OctoMed-7B
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 27 años, acude a consulta por visión ...","<think>Okay, let's tackle this medical questio...",OctoMed-7B
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4185,"¿En qué tipo de neumoconiosis, se puede observ...",Antracosis,Asbestosis,Silicosis,Beriliosis,B,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,"¿En qué tipo de neumoconiosis, se puede observ...","<think>Okay, let's tackle this question about ...",OctoMed-7B
4186,¿Cuál es la enfermedad neurológica típica caus...,Wernicke-Korsakoff,Tay-Sachs,Niemann-Pick,Krabbe,A,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es la enfermedad neurológica típica caus...,"<think>Okay, the question is asking about a ne...",OctoMed-7B
4187,¿Cuál de las siguientes enfermedades autoinmun...,Anemia hemolítica autoinmune,Miastenia Gravis,Síndrome de Goodpasture,DM tipo 1,D,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál de las siguientes enfermedades autoinmun...,"<think>Okay, I need to figure out which of the...",OctoMed-7B
4188,¿Qué glomerulonefritis causa síndrome nefrótic...,Postinfecciosa,Membranoproliferativa,Membranosa,Rapidamente progresiva,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Qué glomerulonefritis causa síndrome nefrótic...,"<think>Okay, let's tackle this question step b...",OctoMed-7B
4189,En la inflamación aguda. ¿Qué mediador químico...,Selectinas,Opsoninas,Integrinas,Complemento C3,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,En la inflamación aguda. ¿Qué mediador químico...,"<think>Okay, the question is about which chemi...",OctoMed-7B

In [3]:
# df['letra_respuesta'] = df['answer_llm'].str.extract(r'Respuesta final: ([ABCDE])')
# df['letra_respuesta'] = df['answer_llm'].str.extract(r'Respuesta final:\(?([ABCDE])\)?')
df['letra_respuesta'] = df['answer_llm'].str.extract(r'Respuesta final:\s?\(?([ABCDE])\)?')
df

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename,letra_respuesta
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025,Varón de 65 años con antecedente de hipertensi...,"<think>Okay, let's tackle this medical questio...",OctoMed-7B,A
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025,Mujer de 32 años asintomática que acude por ch...,"<think>Okay, let's tackle this medical questio...",OctoMed-7B,A
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025,¿Cuál es el sitio más frecuente de implantació...,"<think>Okay, the question is asking about the ...",OctoMed-7B,A
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 43 años, llevado a urgencias porque s...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,D
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 27 años, acude a consulta por visión ...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4185,"¿En qué tipo de neumoconiosis, se puede observ...",Antracosis,Asbestosis,Silicosis,Beriliosis,B,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,"¿En qué tipo de neumoconiosis, se puede observ...","<think>Okay, let's tackle this question about ...",OctoMed-7B,B
4186,¿Cuál es la enfermedad neurológica típica caus...,Wernicke-Korsakoff,Tay-Sachs,Niemann-Pick,Krabbe,A,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es la enfermedad neurológica típica caus...,"<think>Okay, the question is asking about a ne...",OctoMed-7B,A
4187,¿Cuál de las siguientes enfermedades autoinmun...,Anemia hemolítica autoinmune,Miastenia Gravis,Síndrome de Goodpasture,DM tipo 1,D,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál de las siguientes enfermedades autoinmun...,"<think>Okay, I need to figure out which of the...",OctoMed-7B,D
4188,¿Qué glomerulonefritis causa síndrome nefrótic...,Postinfecciosa,Membranoproliferativa,Membranosa,Rapidamente progresiva,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Qué glomerulonefritis causa síndrome nefrótic...,"<think>Okay, let's tackle this question step b...",OctoMed-7B,C
4189,En la inflamación aguda. ¿Qué mediador químico...,Selectinas,Opsoninas,Integrinas,Complemento C3,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,En la inflamación aguda. ¿Qué mediador químico...,"<think>Okay, the question is about which chemi...",OctoMed-7B,C

In [4]:
df['letra_respuesta'].value_counts(dropna = False)

letra_respuesta
C      983
B      957
D      895
A      872
E      476
NaN      7
Name: count, dtype: int64

In [5]:
df[df['letra_respuesta'].isna()][['question', 'answer_llm', 'letra_respuesta']]   # Manually verified that these 09 cases do not contain a valid answer.

,question,answer_llm,letra_respuesta
184,"Niño de 11 años, traído a urgencias por 5 días...","<think>Okay, let's tackle this pediatric emerg...",NaN
503,Varón de 33 años. TC: proceso expansivo el cua...,"<think>Okay, let's tackle this question about ...",NaN
1440,¿Durante qué parte del ciclo cardíaco está abi...,"<think>Okay, I need to figure out during which...",NaN
2444,¿Cuál es considerado un tumor cerebral secunda...,"<think>Okay, let's tackle this question about ...",NaN
2825,"Gestante de 39 semanas, grupo sanguíneo A(+ ),...","<think>Okay, let's tackle this question step b...",NaN
3492,¿Cuál de los siguientes neurotransmisores actú...,"<think>Okay, the question is asking which neur...",NaN
3724,"Niño de 3 años, quien ha presentado 3 episodio...","<think>Okay, let's tackle this question step b...",NaN

In [6]:
df = df.dropna(subset='letra_respuesta')
df = df.reset_index(drop=True)
df.shape

(4183, 14)

In [7]:
pd.crosstab(df['correct_answer'], df['letra_respuesta'], normalize='columns')

letra_respuesta         A         B         C         D         E
correct_answer
A                0.776376  0.058516  0.047813  0.041341  0.117647
B                0.058486  0.820272  0.039674  0.048045  0.117647
C                0.088303  0.060606  0.857579  0.043575  0.168067
D                0.060780  0.051202  0.040692  0.842458  0.132353
E                0.016055  0.009404  0.014242  0.024581  0.464286

In [8]:
# df['is_correct'] = df['correct_answer'] == df['letra_respuesta']

# results = df.groupby(['source_file', 'year']).agg(
#     count_of_matches=('is_correct', 'sum'),
#     total_rows=('is_correct', 'size')
# ).reset_index()
# results['percent_correct'] = (results['count_of_matches'] / results['total_rows']) * 100
# results['percent_correct'] = results['percent_correct'].round(2)
# # results['performance'] = (results['percent_correct'] >= 52).astype(int)
# # results[results['performance'] == 1]
# results

########################################################################################################################################################################################################

In [9]:
df2 = pd.read_pickle('/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/10.OctoMed-7B/Chunk_2/combined_exam_dataset_OctoMed-7B_chunk2.pickle')
df2

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename
4190,¿Cuál es el trastorno predisponente más import...,Cirugía abdominal previa,Enfermedad inflamatoria pélvica previa,Endometriosis,Uso de dispositivos intrauterinos,B,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es el trastorno predisponente más import...,"<think>Okay, the question is asking about the ...",OctoMed-7B
4191,¿Cuál es la manifestación inicial más frecuent...,Sindrome de Zollinger-Ellison,Prolactinomas,Hiperparatiroidismo primario,Gastrinomas,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es la manifestación inicial más frecuent...,"<think>Okay, the question is asking about the ...",OctoMed-7B
4192,¿Cuál es el tumor del infante que se localiza ...,Ependimoma,Astrocitoma,Meduloblastoma,Oligodendroglioma.,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es el tumor del infante que se localiza ...,"<think>Okay, let's tackle this question. The u...",OctoMed-7B
4193,¿Cuál de las variantes histológicas del carcin...,Fibrolamelar,Escirro,Sarcomatoide,Linfoepitelioide,A,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál de las variantes histológicas del carcin...,"<think>Okay, let's tackle this question about ...",OctoMed-7B
4194,En la amiloidosis sistémica. ¿Qué tipo de prot...,ATTR,Aβ,Aβ2m,AA,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,En la amiloidosis sistémica. ¿Qué tipo de prot...,"<think>Okay, let's tackle this question about ...",OctoMed-7B
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8375,Gestante de 20 años con 10 semanas de embarazo...,Epigastralgia,Meteorismo,Pérdida de peso menor al 5%,Presencia de aliento fétido,E,Alteraciones hidroelectrolíticas,Ginecología y Obstetricia,Year2020,2020,Gestante de 20 años con 10 semanas de embarazo...,"<think>Okay, let's tackle this question about ...",OctoMed-7B
8376,"Mujer de 40 años ha tenido 4 partos eutócicos,...",Mola hidatidiforme,Hematometra,Tumor anexial,Miomatosis uterina,A,Embarazo gemelar,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años ha tenido 4 partos eutócicos,...","<think>Okay, let's tackle this medical questio...",OctoMed-7B
8377,"Mujer de 40 años, refiere menstruaciones regul...",Biopsia en sacabocado y curetaje cervical,Histerectomía inmediata y extirpación de,Repetir el frotis de Papanicolaou y control a los,Colposcopía con biopsia,D,Dilatación y legrado fraccionado,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años, refiere menstruaciones regul...","<think>Okay, let's tackle this medical questio...",OctoMed-7B
8378,"De los siguientes exámenes o procedimientos, ¿...",Eco transvaginal,Eco doppler transvaginal,Cultivo de secreción vaginal,Histeroscopía,E,Laparoscopia,Ginecología y Obstetricia,Year2020,2020,"De los siguientes exámenes o procedimientos, ¿...","<think>Okay, let's tackle this question about ...",OctoMed-7B
8379,Si usted fuera el encargado de determinar que ...,Bloqueo tubárico,DIU,Preservativo,Diafragma,E,Vasectomía,Ginecología y Obstetricia,Year2020,2020,Si usted fuera el encargado de determinar que ...,"<think>Okay, the user is asking which contrace...",OctoMed-7B

In [10]:
df2['letra_respuesta'] = df2['answer_llm'].str.extract(r'Respuesta final:\s?\(?([ABCDE])\)?')
df2

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename,letra_respuesta
4190,¿Cuál es el trastorno predisponente más import...,Cirugía abdominal previa,Enfermedad inflamatoria pélvica previa,Endometriosis,Uso de dispositivos intrauterinos,B,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es el trastorno predisponente más import...,"<think>Okay, the question is asking about the ...",OctoMed-7B,B
4191,¿Cuál es la manifestación inicial más frecuent...,Sindrome de Zollinger-Ellison,Prolactinomas,Hiperparatiroidismo primario,Gastrinomas,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es la manifestación inicial más frecuent...,"<think>Okay, the question is asking about the ...",OctoMed-7B,C
4192,¿Cuál es el tumor del infante que se localiza ...,Ependimoma,Astrocitoma,Meduloblastoma,Oligodendroglioma.,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál es el tumor del infante que se localiza ...,"<think>Okay, let's tackle this question. The u...",OctoMed-7B,C
4193,¿Cuál de las variantes histológicas del carcin...,Fibrolamelar,Escirro,Sarcomatoide,Linfoepitelioide,A,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,¿Cuál de las variantes histológicas del carcin...,"<think>Okay, let's tackle this question about ...",OctoMed-7B,A
4194,En la amiloidosis sistémica. ¿Qué tipo de prot...,ATTR,Aβ,Aβ2m,AA,C,Ninguna de las anteriores,Anatomía Patológica & Patología,Year2024,2024,En la amiloidosis sistémica. ¿Qué tipo de prot...,"<think>Okay, let's tackle this question about ...",OctoMed-7B,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8375,Gestante de 20 años con 10 semanas de embarazo...,Epigastralgia,Meteorismo,Pérdida de peso menor al 5%,Presencia de aliento fétido,E,Alteraciones hidroelectrolíticas,Ginecología y Obstetricia,Year2020,2020,Gestante de 20 años con 10 semanas de embarazo...,"<think>Okay, let's tackle this question about ...",OctoMed-7B,E
8376,"Mujer de 40 años ha tenido 4 partos eutócicos,...",Mola hidatidiforme,Hematometra,Tumor anexial,Miomatosis uterina,A,Embarazo gemelar,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años ha tenido 4 partos eutócicos,...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,A
8377,"Mujer de 40 años, refiere menstruaciones regul...",Biopsia en sacabocado y curetaje cervical,Histerectomía inmediata y extirpación de,Repetir el frotis de Papanicolaou y control a los,Colposcopía con biopsia,D,Dilatación y legrado fraccionado,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años, refiere menstruaciones regul...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,D
8378,"De los siguientes exámenes o procedimientos, ¿...",Eco transvaginal,Eco doppler transvaginal,Cultivo de secreción vaginal,Histeroscopía,E,Laparoscopia,Ginecología y Obstetricia,Year2020,2020,"De los siguientes exámenes o procedimientos, ¿...","<think>Okay, let's tackle this question about ...",OctoMed-7B,E
8379,Si usted fuera el encargado de determinar que ...,Bloqueo tubárico,DIU,Preservativo,Diafragma,E,Vasectomía,Ginecología y Obstetricia,Year2020,2020,Si usted fuera el encargado de determinar que ...,"<think>Okay, the user is asking which contrace...",OctoMed-7B,E

In [11]:
df2['letra_respuesta'].value_counts(dropna = False)

letra_respuesta
B      918
A      871
D      871
C      823
E      699
NaN      8
Name: count, dtype: int64

In [12]:
df2[df2['letra_respuesta'].isna()][['question', 'answer_llm', 'letra_respuesta']]   # Manually verified that these 09 cases do not contain a valid answer.

,question,answer_llm,letra_respuesta
4592,Al considerar sospecha de neuropatía por compr...,"<think>Okay, let's tackle this question step b...",NaN
4854,¿Qué se espera encontrar en la miastenia ocula...,"<think>Okay, let's tackle this question about ...",NaN
6404,Neonato prematuro. Examen: bolsas escrotales h...,"<think>Okay, let's tackle this question step b...",NaN
6942,"Varón de 65 años, hipertenso controlado, con d...","<think>Okay, let's tackle this medical questio...",NaN
7170,¿Cuál es la mejor prueba gammagráfica para det...,"<think>Okay, let's tackle this question about ...",NaN
7363,Mujer de 45 años con antecedente de hemorragia...,"<think>Okay, let's tackle this question step b...",NaN
7404,Hombre 40 años que sufre accidente de tránsito...,"<think>Okay, let's tackle this question step b...",NaN
7477,En la evaluación de un paciente que ingresa po...,"<think>Okay, let's tackle this question about ...",NaN

In [13]:
df2 = df2.dropna(subset=['letra_respuesta'])
df2 = df2.reset_index(drop=True)
df2.shape

(4182, 14)

In [14]:
pd.crosstab(df2['correct_answer'], df2['letra_respuesta'], normalize='columns')

letra_respuesta         A         B         C         D         E
correct_answer
A                0.769231  0.079521  0.057108  0.051665  0.091559
B                0.061998  0.760349  0.051033  0.052813  0.051502
C                0.055109  0.056645  0.788578  0.034443  0.048641
D                0.072331  0.059913  0.071689  0.831228  0.085837
E                0.041332  0.043573  0.031592  0.029851  0.722461

########################################################################################################################################################################################################

In [15]:
df3 = pd.concat([df, df2], ignore_index=True)
df3

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year,question,answer_llm,model_basename,letra_respuesta
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025,Varón de 65 años con antecedente de hipertensi...,"<think>Okay, let's tackle this medical questio...",OctoMed-7B,A
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025,Mujer de 32 años asintomática que acude por ch...,"<think>Okay, let's tackle this medical questio...",OctoMed-7B,A
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025,¿Cuál es el sitio más frecuente de implantació...,"<think>Okay, the question is asking about the ...",OctoMed-7B,A
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 43 años, llevado a urgencias porque s...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,D
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025,"Varón de 27 años, acude a consulta por visión ...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8360,Gestante de 20 años con 10 semanas de embarazo...,Epigastralgia,Meteorismo,Pérdida de peso menor al 5%,Presencia de aliento fétido,E,Alteraciones hidroelectrolíticas,Ginecología y Obstetricia,Year2020,2020,Gestante de 20 años con 10 semanas de embarazo...,"<think>Okay, let's tackle this question about ...",OctoMed-7B,E
8361,"Mujer de 40 años ha tenido 4 partos eutócicos,...",Mola hidatidiforme,Hematometra,Tumor anexial,Miomatosis uterina,A,Embarazo gemelar,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años ha tenido 4 partos eutócicos,...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,A
8362,"Mujer de 40 años, refiere menstruaciones regul...",Biopsia en sacabocado y curetaje cervical,Histerectomía inmediata y extirpación de,Repetir el frotis de Papanicolaou y control a los,Colposcopía con biopsia,D,Dilatación y legrado fraccionado,Ginecología y Obstetricia,Year2020,2020,"Mujer de 40 años, refiere menstruaciones regul...","<think>Okay, let's tackle this medical questio...",OctoMed-7B,D
8363,"De los siguientes exámenes o procedimientos, ¿...",Eco transvaginal,Eco doppler transvaginal,Cultivo de secreción vaginal,Histeroscopía,E,Laparoscopia,Ginecología y Obstetricia,Year2020,2020,"De los siguientes exámenes o procedimientos, ¿...","<think>Okay, let's tackle this question about ...",OctoMed-7B,E
8364,Si usted fuera el encargado de determinar que ...,Bloqueo tubárico,DIU,Preservativo,Diafragma,E,Vasectomía,Ginecología y Obstetricia,Year2020,2020,Si usted fuera el encargado de determinar que ...,"<think>Okay, the user is asking which contrace...",OctoMed-7B,E

In [16]:
df3['is_correct'] = df3['correct_answer'] == df3['letra_respuesta']

results = df3.groupby(['source_file', 'year']).agg(
    count_of_matches=('is_correct', 'sum'),
    total_rows=('is_correct', 'size')
).reset_index()
results['percent_correct'] = (results['count_of_matches'] / results['total_rows']) * 100
results['percent_correct'] = results['percent_correct'].round(2)
# results['performance'] = (results['percent_correct'] >= 52).astype(int)
# results[results['performance'] == 1]
results

,source_file,year,count_of_matches,total_rows,percent_correct
0,Anatomía Patológica & Patología,2018,79,100,79.0
1,Anatomía Patológica & Patología,2019,75,100,75.0
2,Anatomía Patológica & Patología,2020,83,100,83.0
3,Anatomía Patológica & Patología,2023,82,100,82.0
4,Anatomía Patológica & Patología,2024,81,100,81.0
...,...,...,...,...,...
78,Urología,2020,73,100,73.0
79,Urología,2022,81,100,81.0
80,Urología,2023,79,100,79.0
81,Urología,2024,71,100,71.0
82,Urología,2025,79,100,79.0

########################################################################################################################################################################################################

In [17]:
results['model_name'] = 'OctoMed-7B'
results.to_pickle('/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/10.OctoMed-7B/_Results.pickle')