In [1]:
import pandas as pd
import random

In [2]:
df = pd.read_pickle('/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/01.Datasets/combined_exam_dataset.pkl')
df

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025
...,...,...,...,...,...,...,...,...,...,...
8375,Gestante de 20 años con 10 semanas de embarazo...,Epigastralgia,Meteorismo,Pérdida de peso menor al 5%,Presencia de aliento fétido,E,Alteraciones hidroelectrolíticas,Ginecología y Obstetricia,Year2020,2020
8376,"Mujer de 40 años ha tenido 4 partos eutócicos,...",Mola hidatidiforme,Hematometra,Tumor anexial,Miomatosis uterina,A,Embarazo gemelar,Ginecología y Obstetricia,Year2020,2020
8377,"Mujer de 40 años, refiere menstruaciones regul...",Biopsia en sacabocado y curetaje cervical,Histerectomía inmediata y extirpación de,Repetir el frotis de Papanicolaou y control a los,Colposcopía con biopsia,D,Dilatación y legrado fraccionado,Ginecología y Obstetricia,Year2020,2020
8378,"De los siguientes exámenes o procedimientos, ¿...",Eco transvaginal,Eco doppler transvaginal,Cultivo de secreción vaginal,Histeroscopía,E,Laparoscopia,Ginecología y Obstetricia,Year2020,2020
8379,Si usted fuera el encargado de determinar que ...,Bloqueo tubárico,DIU,Preservativo,Diafragma,E,Vasectomía,Ginecología y Obstetricia,Year2020,2020

In [3]:
def shuffle_quiz_options(input_pickle, output_pickle):
    """
    Randomly shuffle multiple-choice options for each question and update the correct answer.
    
    Parameters:
    - input_pickle: path to input pickle file
    - output_pickle: path to output pickle file
    """
    # Read the pickle file
    df = pd.read_pickle(input_pickle)
    
    # Define the option columns
    option_cols = ['option_A', 'option_B', 'option_C', 'option_D', 'option_E']
    option_labels = ['A', 'B', 'C', 'D', 'E']
    
    # Create new columns for shuffled options
    shuffled_data = []
    
    for idx, row in df.iterrows():
        # Get the current correct answer label
        correct_label = row['correct_answer'].strip().upper()
        
        # Create a list of (label, option_text) tuples
        options = [(label, row[col]) for label, col in zip(option_labels, option_cols)]
        
        # Find the correct option text
        correct_idx = option_labels.index(correct_label)
        correct_text = options[correct_idx][1]
        
        # Extract just the option texts
        option_texts = [opt[1] for opt in options]
        
        # Shuffle the option texts
        random.shuffle(option_texts)
        
        # Find the new position of the correct answer
        new_correct_idx = option_texts.index(correct_text)
        new_correct_label = option_labels[new_correct_idx]
        
        # Create a new row with shuffled options
        new_row = row.copy()
        for i, col in enumerate(option_cols):
            new_row[col] = option_texts[i]
        new_row['correct_answer'] = new_correct_label
        
        shuffled_data.append(new_row)
    
    # Create new dataframe with shuffled data
    df_shuffled = pd.DataFrame(shuffled_data)
    
    # Save to pickle
    df_shuffled.to_pickle(output_pickle)
    print(f"Successfully shuffled {len(df_shuffled)} questions.")
    print(f"Output saved to: {output_pickle}")
    
    return df_shuffled

In [4]:
input_file = "/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/01.Datasets/combined_exam_dataset.pkl"  # Change this to your input file name
output_file = "/Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/Reorder Options/combined_exam_dataset_shuffled.pkl"  # Change this to your desired output file name

df_result = shuffle_quiz_options(input_file, output_file)

Successfully shuffled 8380 questions.
Output saved to: /Users/rodrigocarrillo/Documents/Natural Language Processing Projects/Examen Residentado Peru/02.LLMs Results/Reorder Options/combined_exam_dataset_shuffled.pkl

In [5]:
df_result.head()

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year
0,Varón de 65 años con antecedente de hipertensi...,Nitroprusiato,Hidralazina,Nitroglicerina,Labetalol,A,Ninguna de las anteriores,Prueba A,Year2025,2025
1,Mujer de 32 años asintomática que acude por ch...,Ecografía de mamas,Ninguna de las anteriores,Mamografía,Observación,D,Solicitar prolactina,Prueba A,Year2025,2025
2,¿Cuál es el sitio más frecuente de implantació...,Ninguna de las anteriores,Cérvix uterino,Segmento inferior del útero,Fondo uterino,D,Cuerno uterino,Prueba A,Year2025,2025
3,"Varón de 43 años, llevado a urgencias porque s...",Intubación orotraqueal,Ventilación no invasiva,Fijación costal quirúrgica,Colocación de catéter central,A,Ninguna de las anteriores,Prueba A,Year2025,2025
4,"Varón de 27 años, acude a consulta por visión ...",Ninguna de las anteriores,I,III,VI,C,IV,Prueba A,Year2025,2025

In [6]:
df.head()

,questions,option_A,option_B,option_C,option_D,correct_answer,option_E,source_file,source_folder,year
0,Varón de 65 años con antecedente de hipertensi...,Labetalol,Hidralazina,Nitroprusiato,Nitroglicerina,C,Ninguna de las anteriores,Prueba A,Year2025,2025
1,Mujer de 32 años asintomática que acude por ch...,Solicitar prolactina,Mamografía,Ecografía de mamas,Observación,D,Ninguna de las anteriores,Prueba A,Year2025,2025
2,¿Cuál es el sitio más frecuente de implantació...,Fondo uterino,Segmento inferior del útero,Cérvix uterino,Cuerno uterino,A,Ninguna de las anteriores,Prueba A,Year2025,2025
3,"Varón de 43 años, llevado a urgencias porque s...",Colocación de catéter central,Ventilación no invasiva,Fijación costal quirúrgica,Intubación orotraqueal,D,Ninguna de las anteriores,Prueba A,Year2025,2025
4,"Varón de 27 años, acude a consulta por visión ...",VI,I,III,IV,C,Ninguna de las anteriores,Prueba A,Year2025,2025